name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Code checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build & push backend
      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/loan-backend ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/loan-backend

      # 5. Build & push frontend
      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/loan-frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/loan-frontend
